### ISSUE TITLE
Ensure data & account permanent persistence before w3up-cli alpha release

### ISSUE THREAD

**Issue by JeffLowe** [nftstorage/w3up-cli#39]
## Overview
In order to be considered "Alpha Release", uploads must permanently persist, user accounts must permanently persist, and users must have a way of retrieving and/or relinking of uploads with accounts. 

## requirements / tasks
- [x] Stickiness of CID uploading.  writing CIDs uploaded to the log at a minimum (accomplished in #30 )
- [x] Stickiness of everything else (DID account not blown away with dev service)
- [x] Stickiness of existing account linking

- [x] @ice-breaker-tg sync with @hugomrdias to move off of staging S3 bucket

**Comment by jchris** [comment]
@hugomrdias @Gozala can y'all help make sure there are no blockers here?

**Comment by hugomrdias** [comment]
account DID will change with the new account system presented by @Gozala 

what does "Stickiness of existing account linking" mean ?

**Comment by jchris** [comment]
Need to sync with @hugomrdias to move off of staging S3 bucket

**Comment by jchris** [comment]
Account DIDs for accounts might change. Old DIDs can be linked to new accounts as part of a migration.

**Comment by jchris** [comment]
Lets beeline to get the "same" bucket happening.

**Comment by the-simian** [comment]
A this point, everything that needs to happen in the w3up codebase - to our knowledge is happening. I'm going to close this now. Everything is using the production endpoints and we've verified the bucket is hitting EIPFS and propagating to IPFS downstream
